'use strict';

var mongoose = require('mongoose'),
  Product = mongoose.model('Product');

/**
 * Populate database with sample application data
 */

// Clear old item names, then add a default names
Product.find({}).remove(function() {
  Product.create(
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_3401_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens running shoes",
        "user"              : "Women",
        "activity"          : "Running",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 6, 7, 8, 9, 10, 11, 12, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/T3N2N_7501_0010198277_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids training shoes",
        "user"              : "Kids",
        "activity"          : "Training",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5, 12.5 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n2n_9001_0010198277_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens basketball shoes",
        "user"              : "Men",
        "activity"          : "Basketball",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 6.5, 8, 8.5, 10, 10.5, 12, 12.5 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/T3N7Q_3631_0010214549_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens football shoes",
        "user"              : "Women",
        "activity"          : "Football",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 7, 7.5, 9, 9.5, 11, 11.5, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_4001_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids martial arts shoes",
        "user"              : "Kids",
        "activity"          : "Martial Arts",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 6, 6.5, 7, 8, 8.5, 9, 10, 10.5, 11, 12, 12.5, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_3401_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens running shoes",
        "user"              : "Men",
        "activity"          : "Running",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 6, 7, 7.5, 8, 9, 9.5, 10, 11, 11.5, 12, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_3401_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens training shoes",
        "user"              : "Women",
        "activity"          : "Training",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5.5, 6, 6.5, 7.5, 8, 8.5, 9.5, 10, 10.5, 11.5, 12, 12.5 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/T3N2N_7501_0010198277_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids basketball shoes",
        "user"              : "Kids",
        "activity"          : "Basketball",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 6.5, 7, 7.5, 8.5, 9, 9.5, 10.5, 11, 11.5, 12.5, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n2n_9001_0010198277_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens football shoes",
        "user"              : "Men",
        "activity"          : "Football",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5.5, 6, 7, 7.5, 8.5, 9, 10, 10.5, 11.5, 12, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/T3N7Q_3631_0010214549_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens martial arts shoes",
        "user"              : "Women",
        "activity"          : "Martial Arts",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 6, 6.5, 7.5, 8, 9, 9.5, 10.5, 11, 12, 12.5 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_4001_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids running shoes",
        "user"              : "Kids",
        "activity"          : "Running",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 6, 7.5, 8, 8.5, 10, 10.5, 11, 12.5, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_3401_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens training shoes",
        "user"              : "Men",
        "activity"          : "Training",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 7, 7.5, 8, 9.5, 10, 10.5, 12, 12.5, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_3401_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens basketball shoes",
        "user"              : "Women",
        "activity"          : "Basketball",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 6, 6.5, 7, 9, 9.5, 11, 11.5, 12, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/T3N2N_7501_0010198277_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids football shoes",
        "user"              : "Kids",
        "activity"          : "Football",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 6, 7, 8, 9, 10, 11, 12, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n2n_9001_0010198277_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens martial arts shoes",
        "user"              : "Women",
        "activity"          : "Martial Arts",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5, 12.5 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/T3N7Q_3631_0010214549_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids running shoes",
        "user"              : "Kids",
        "activity"          : "Running",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 6.5, 8, 8.5, 10, 10.5, 12, 12.5 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_4001_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens training shoes",
        "user"              : "Men",
        "activity"          : "Training",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 7, 7.5, 9, 9.5, 11, 11.5, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_3401_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens basketball shoes",
        "user"              : "Women",
        "activity"          : "Basketball",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 6, 6.5, 7, 8, 8.5, 9, 10, 10.5, 11, 12, 12.5, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_3401_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids football shoes",
        "user"              : "Kids",
        "activity"          : "Football",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 6, 7, 7.5, 8, 9, 9.5, 10, 11, 11.5, 12, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/T3N2N_7501_0010198277_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens martial arts shoes",
        "user"              : "Men",
        "activity"          : "Martial Arts",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5.5, 6, 6.5, 7.5, 8, 8.5, 9.5, 10, 10.5, 11.5, 12, 12.5 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n2n_9001_0010198277_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens running shoes",
        "user"              : "Women",
        "activity"          : "Running",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 6.5, 7, 7.5, 8.5, 9, 9.5, 10.5, 11, 11.5, 12.5, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/T3N7Q_3631_0010214549_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids training shoes",
        "user"              : "Kids",
        "activity"          : "Training",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5.5, 6, 7, 7.5, 8.5, 9, 10, 10.5, 11.5, 12, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_4001_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens basketball shoes",
        "user"              : "Men",
        "activity"          : "Basketball",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 6, 6.5, 7.5, 8, 9, 9.5, 10.5, 11, 12, 12.5 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_3401_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens football shoes",
        "user"              : "Women",
        "activity"          : "Football",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 6, 7.5, 8, 8.5, 10, 10.5, 11, 12.5, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_3401_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids martial arts shoes",
        "user"              : "Kids",
        "activity"          : "Martial Arts",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 7, 7.5, 8, 9.5, 10, 10.5, 12, 12.5, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/T3N2N_7501_0010198277_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens running shoes",
        "user"              : "Men",
        "activity"          : "Running",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 6, 6.5, 7, 9, 9.5, 11, 11.5, 12, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n2n_9001_0010198277_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens training shoes",
        "user"              : "Women",
        "activity"          : "Training",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 6, 7, 8, 9, 10, 11, 12, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/T3N7Q_3631_0010214549_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids basketball shoes",
        "user"              : "Kids",
        "activity"          : "Basketball",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5, 12.5 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_4001_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens football shoes",
        "user"              : "Men",
        "activity"          : "Football",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 6.5, 8, 8.5, 10, 10.5, 12, 12.5 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_3401_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens martial arts shoes",
        "user"              : "Women",
        "activity"          : "Martial Arts",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13 ]
    },
    function() {
      console.log('finished populating products');
    }
  );
});
