'use strict';

var mongoose = require('mongoose'),
  Product = mongoose.model('Product');

/**
 * Populate database with sample application data
 */

// Clear old item names, then add a default names
Product.find({}).remove(function() {
  Product.create(
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_3401_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens running shoes",
        "user"              : "men",
        "activity"          : "Basketball",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        'sizes'             : [ 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 15, 16, 17, 18 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/T3N2N_7501_0010198277_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens running shoes",
        "user"              : "men",
        "activity"          : "Basketball",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        'sizes'             : [ 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 15, 16, 17, 18 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n2n_9001_0010198277_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens running shoes",
        "user"              : "men",
        "activity"          : "Basketball",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        'sizes'             : [ 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 15, 16, 17, 18 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/T3N7Q_3631_0010214549_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens running shoes",
        "user"              : "men",
        "activity"          : "Basketball",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        'sizes'             : [ 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 15, 16, 17, 18 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_4001_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens running shoes",
        "user"              : "men",
        "activity"          : "Basketball",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        'sizes'             : [ 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 15, 16, 17, 18 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/t3n7n_3401_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens running shoes",
        "user"              : "men",
        "activity"          : "Basketball",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        'sizes'             : [ 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 15, 16, 17, 18 ]
    },
    function() {
      console.log('finished populating products');
    }
  );
});
