'use strict';

var mongoose = require('mongoose'),
  Product = mongoose.model('Product');

/**
 * Populate database with sample application data
 */

// Clear old item names, then add a default names
Product.find({}).remove(function() {
  Product.create(
    {
        "product_id"        : 1,
        "manufacturer"      : "Adidas",
        "name"              : "Pure Boost",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/womens/running/adidas-pure-boost-womens.png",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens running shoes",
        "user"              : "Women",
        "activity"          : "Running",
        "description"       : "The Adidas Pure Boost womens running shoes...",
        "short_description" : "The Adidas Pure Boost womens running shoes...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 6, 7, 8, 9, 10, 11, 12, 13 ]
    },
    {
        "product_id"        : 2,
        "manufacturer"      : "Nike",
        "name"              : "Air Max 2014",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/kids/running/nike-air-max-2014-boys-grade-school.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids running shoes",
        "user"              : "Kids",
        "activity"          : "Running",
        "description"       : "The kids' Air Max 2014 boys running...",
        "short_description" : "The kids' Air Max 2014 boys running...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5, 12.5 ]
    },
    {
        "product_id"        : 3,
        "manufacturer"      : "Nike",
        "name"              : "Jordan Flight 2",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/mens/basketball/jordan-1-flight-2-mens.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens basketball shoes",
        "user"              : "Men",
        "activity"          : "Basketball",
        "description"       : "The Jordan Flight 2...",
        "short_description" : "The Jordan Flight 2...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 6.5, 8, 8.5, 10, 10.5, 12, 12.5 ]
    },
    {
        "product_id"        : 4,
        "manufacturer"      : "Diadora",
        "name"              : "Maracana MD PU",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/womens/football/Diadora_Women's_Maracana_MD_PU.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens football shoes",
        "user"              : "Women",
        "activity"          : "Football",
        "description"       : "The Women's Maracana MD PU...jpg",
        "short_description" : "The Women's Maracana MD PU...jpg",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 7, 7.5, 9, 9.5, 11, 11.5, 13 ]
    },
    {
        "product_id"        : 5,
        "manufacturer"      : "Nike",
        "name"              : "Vulcan",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/kids/casual/nike-kd-vulc-boys-grade-school.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids martial arts shoes",
        "user"              : "Kids",
        "activity"          : "Martial Arts",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 6, 6.5, 7, 8, 8.5, 9, 10, 10.5, 11, 12, 12.5, 13 ]
    },
    {
        "product_id"        : 1,
        "manufacturer"      : "Adidas",
        "name"              : "Energy Boost 2",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/mens/running/adidas-energy-boost-2-mens.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens running shoes",
        "user"              : "Men",
        "activity"          : "Running",
        "description"       : "The Energy Boost 2 mens...",
        "short_description" : "The Energy Boost 2 mens...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 6, 7, 7.5, 8, 9, 9.5, 10, 11, 11.5, 12, 13 ]
    },
    {
        "product_id"        : 6,
        "manufacturer"      : "Adidas",
        "name"              : "Powerlift Trainer 2",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/womens/training/adidas-powerlift-trainer-2-womens.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens training shoes",
        "user"              : "Women",
        "activity"          : "Training",
        "description"       : "The Powerlift Trainer 2 womens...",
        "short_description" : "The Powerlift Trainer 2 womens...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5.5, 6, 6.5, 7.5, 8, 8.5, 9.5, 10, 10.5, 11.5, 12, 12.5 ]
    },
    {
        "product_id"        : 7,
        "manufacturer"      : "Nike",
        "name"              : "Jordan Flight 2",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/kids/basketball/jordan-1-flight-2-low-boys-grade-school.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids basketball shoes",
        "user"              : "Kids",
        "activity"          : "Basketball",
        "description"       : "The Jordan Flight 2 kids",
        "short_description" : "The Jordan Flight 2 kids",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 6.5, 7, 7.5, 8.5, 9, 9.5, 10.5, 11, 11.5, 12.5, 13 ]
    },
    {
        "product_id"        : 8,
        "manufacturer"      : "Nike",
        "name"              : "Mercurial Vapor IX FG",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/mens/football/mercurial_vapor_ix_fg_soccer_cleats_metallic_mach_purple-black-total_orange.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens football shoes",
        "user"              : "Men",
        "activity"          : "Football",
        "description"       : "The Mercurial Vapor IX FG mens cleats..",
        "short_description" : "The Mercurial Vapor IX FG mens cleats..",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5.5, 6, 7, 7.5, 8.5, 9, 10, 10.5, 11.5, 12, 13 ]
    },
    {
        "product_id"        : 9,
        "manufacturer"      : "Adidas",
        "name"              : "Originals Superstar 2",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/womens/casual/adidas-originals-superstar-2-womens.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens martial arts shoes",
        "user"              : "Women",
        "activity"          : "Martial Arts",
        "description"       : "The Originals Superstar 2 womens casual...",
        "short_description" : "The Originals Superstar 2 womens casual...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 6, 6.5, 7.5, 8, 9, 9.5, 10.5, 11, 12, 12.5 ]
    },
    {
        "product_id"        : 10,
        "manufacturer"      : "Addidas",
        "name"              : "Springdale Razor",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/kids/running/adidas-springblade-razor-boys-grade-school.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids running shoes",
        "user"              : "Kids",
        "activity"          : "Running",
        "description"       : "The Addidas Springdale Razor boys'..",
        "short_description" : "The Addidas Springdale Razor boys'..",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 6, 7.5, 8, 8.5, 10, 10.5, 11, 12.5, 13 ]
    },
    {
        "product_id"        : 11,
        "manufacturer"      : "Addidas",
        "name"              : "Originals Samoa",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/mens/training/adidas-originals-samoa-mens.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens training shoes",
        "user"              : "Men",
        "activity"          : "Training",
        "description"       : "The Adidas Originals Samoa men's...",
        "short_description" : "The Adidas Originals Samoa men's...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 7, 7.5, 8, 9.5, 10, 10.5, 12, 12.5, 13 ]
    },
    {
        "product_id"        : 12,
        "manufacturer"      : "Addidas",
        "name"              : "Originals Adi High",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/womens/basketball/adidas-originals-adi-high-ext-womens.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens basketball shoes",
        "user"              : "Women",
        "activity"          : "Basketball",
        "description"       : "The Adidas Originals Adi High womens'...",
        "short_description" : "The Adidas Originals Adi High womens'...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 6, 6.5, 7, 9, 9.5, 11, 11.5, 12, 13 ]
    },
    {
        "product_id"        : 13,
        "manufacturer"      : "Adidas",
        "name"              : "11Nova TRX FG",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/kids/football/adidas_kids_11nova_trx_fg_soccer_cleats.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids football shoes",
        "user"              : "Kids",
        "activity"          : "Football",
        "description"       : "The Adidas kids 11Nova TRX FG...",
        "short_description" : "The Adidas kids 11Nova TRX FG...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 6, 7, 8, 9, 10, 11, 12, 13 ]
    },
    {
        "product_id"        : 14,
        "manufacturer"      : "Puma",
        "name"              : "Soleil FS",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/womens/casual/puma-soleil-fs-womens.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens martial arts shoes",
        "user"              : "Women",
        "activity"          : "Martial Arts",
        "description"       : "The Soleil FS womens..",
        "short_description" : "The Soleil FS womens..",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5, 12.5 ]
    },
    {
        "product_id"        : 15,
        "manufacturer"      : "Adidas",
        "name"              : "Springdale Razor",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/kids/running/adidas-springblade-razor-girls-grade-school.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids running shoes",
        "user"              : "Kids",
        "activity"          : "Running",
        "description"       : "The Adidas Springdale Razor Girls'...",
        "short_description" : "The Adidas Springdale Razor Girls'...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 6.5, 8, 8.5, 10, 10.5, 12, 12.5 ]
    },
    {
        "product_id"        : 16,
        "manufacturer"      : "Adidas",
        "name"              : "Powerlift Trainer",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/mens/training/adidas-powerlift-trainer-2-mens.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens training shoes",
        "user"              : "Men",
        "activity"          : "Training",
        "description"       : "The Adidas Powerlift Trainer...",
        "short_description" : "The Adidas Powerlift Trainer...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 7, 7.5, 9, 9.5, 11, 11.5, 13 ]
    },
    {
        "product_id"        : 17,
        "manufacturer"      : "Adidas",
        "name"              : "Originals Court Attitude",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/womens/basketball/adidas-originals-court-attitude-womens.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens basketball shoes",
        "user"              : "Women",
        "activity"          : "Basketball",
        "description"       : "The Addidas women's Originals Court Attitude...",
        "short_description" : "The Addidas women's Originals Court Attitude...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 6, 6.5, 7, 8, 8.5, 9, 10, 10.5, 11, 12, 12.5, 13 ]
    },
    {
        "product_id"        : 18,
        "manufacturer"      : "Mitre",
        "name"              : "Velocity",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/kids/football/mitre_boys_velocity_soccer_cleats.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids football shoes",
        "user"              : "Kids",
        "activity"          : "Football",
        "description"       : "The kids' Velocity cleats...",
        "short_description" : "The kids' Velocity cleats...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 6, 7, 7.5, 8, 9, 9.5, 10, 11, 11.5, 12, 13 ]
    },
    {
        "product_id"        : 19,
        "manufacturer"      : "Adidas",
        "name"              : "Originals Superstar 2",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/mens/casual/adidas-originals-superstar-2-mens.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens martial arts shoes",
        "user"              : "Men",
        "activity"          : "Martial Arts",
        "description"       : "The Originals Superstar 2 mens casual",
        "short_description" : "The Originals Superstar 2 mens casual",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5.5, 6, 6.5, 7.5, 8, 8.5, 9.5, 10, 10.5, 11.5, 12, 12.5 ]
    },
    {
        "product_id"        : 20,
        "manufacturer"      : "Nike",
        "name"              : "Free 5.0",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/womens/running/nike-free-5.0-2014-womens.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens running shoes",
        "user"              : "Women",
        "activity"          : "Running",
        "description"       : "The Free 5.0 womens running shoes...",
        "short_description" : "The Free 5.0 womens running shoes...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 6.5, 7, 7.5, 8.5, 9, 9.5, 10.5, 11, 11.5, 12.5, 13 ]
    },
    {
        "product_id"        : 21,
        "manufacturer"      : "Nike",
        "name"              : "Air Max 2014",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/kids/running/nike-air-max-2014-girls-grade-school.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids training shoes",
        "user"              : "Kids",
        "activity"          : "Training",
        "description"       : "The Air Max 2014 girls running shoes...",
        "short_description" : "The Air Max 2014 girls running shoes...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5.5, 6, 7, 7.5, 8.5, 9, 10, 10.5, 11.5, 12, 13 ]
    },
    {
        "product_id"        : 22,
        "manufacturer"      : "Nike",
        "name"              : "Jordan AJ",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/mens/basketball/jordan-aj-1-86-mens.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens basketball shoes",
        "user"              : "Men",
        "activity"          : "Basketball",
        "description"       : "The Jordan AJ 86 mens basketball shoes...",
        "short_description" : "The Jordan AJ 86 mens basketball shoes...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 6, 6.5, 7.5, 8, 9, 9.5, 10.5, 11, 12, 12.5 ]
    },
    {
        "product_id"        : 23,
        "manufacturer"      : "Nike",
        "name"              : "Hypervenom Phelon",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/womens/football/Nike_Women's_Hypervenom_Phelon_FG_Soccer_Cleats.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens football shoes",
        "user"              : "Women",
        "activity"          : "Football",
        "description"       : "The Hypervenom Phelon women's football shoes...",
        "short_description" : "The Hypervenom Phelon women's football shoes...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 6, 7.5, 8, 8.5, 10, 10.5, 11, 12.5, 13 ]
    },
    {
        "product_id"        : 24,
        "manufacturer"      : "Nike",
        "name"              : "Air Max 90",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/kids/casual/nike-air-max-90-boys-grade-school.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids martial arts shoes",
        "user"              : "Kids",
        "activity"          : "Martial Arts",
        "description"       : "The Air Max 90 boys casual shoes...",
        "short_description" : "The Air Max 90 boys casual shoes...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : true,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 7, 7.5, 8, 9.5, 10, 10.5, 12, 12.5, 13 ]
    },
    {
        "product_id"        : 25,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/T3N2N_7501_0010198277_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens running shoes",
        "user"              : "Men",
        "activity"          : "Running",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 6, 6.5, 7, 9, 9.5, 11, 11.5, 12, 13 ]
    },
    {
        "product_id"        : 26,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/t3n2n_9001_0010198277_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens training shoes",
        "user"              : "Women",
        "activity"          : "Training",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 6, 7, 8, 9, 10, 11, 12, 13 ]
    },
    {
        "product_id"        : 27,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/T3N7Q_3631_0010214549_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "kids basketball shoes",
        "user"              : "Kids",
        "activity"          : "Basketball",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5, 12.5 ]
    },
    {
        "product_id"        : 28,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/t3n7n_4001_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "mens football shoes",
        "user"              : "Men",
        "activity"          : "Football",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 6.5, 8, 8.5, 10, 10.5, 12, 12.5 ]
    },
    {
        "product_id"        : 29,
        "manufacturer"      : "Asics",
        "name"              : "GEL-KAYANO 20",
        "color"             : "Wht/Royal",
        "vendor"            : "Rachels Sporting Supply",
        "upc"               : "55088707",
        "src"               : "images/shoes/t3n7n_3401_0010198281_f_d_primary.jpg",
        "link"              : "http://www.ggsportif.com/shoes/running/womens/GEL-KAYANO-20/p/0010198281.3401",
        "category"          : "Shoes",
        "sub_category"      : "womens martial arts shoes",
        "user"              : "Women",
        "activity"          : "Martial Arts",
        "description"       : "The Jordan Retro 1 offers you the old-school Jordan look you've always coveted and the world-class style you've come to expect. Leather upper with the legendary Air Jordan wings logo on the side. Air-Sole® unit in the heel and a solid rubber outsole for traction.",
        "short_description" : "The GEL-Kayano 20 is ideal for the serious runner who experiences mild to moderate over-pronation. Maintaining it’s trademark comfort, support and ...",
        "availability"      : "Check Availability",
        "suggestedPrice"    : "59.99",
        "currentPrice"      : "49.99",
        "salePrice"         : "39.99",
        "available"         : false,
        "on_sale"           : true,
        "stock"             : 50,
        "sizes"             : [ 0, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13 ]
    },
    function() {
      console.log('finished populating products');
    }
  );
});
